name: Integration Test

on:
  push:
    branches:
      - main
    paths:
      - build.json
      - config.json
      - Dockerfile
      - rootfs/**
      - .devcontainer/**
  pull_request:
    branches:
      - main
    paths:
      - build.json
      - config.json
      - Dockerfile
      - rootfs/**
      - .devcontainer/**

jobs:
  integration:
    name: Integration test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out repository
        uses: actions/checkout@v6.0.2

      - name: Run integration test in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            if [ -n "${DEBUG:-}" ]; then
              SUPERVISOR_UNCONFINED=1 supervisor_run &
            else
              SUPERVISOR_UNCONFINED=1 supervisor_run > /dev/null 2>&1 &
            fi
            bash .devcontainer/setup-ha.sh
